/**
 * Config padrão do Neuro Designer.
 * Usado pelo BuilderPanel, Gerador de Imagem (fluxo) e Carrossel para enviar
 * uma config completa à API e obter o mesmo prompt estruturado (sujeito, nicho,
 * ambiente, cores, enquadramento, estilo, referências, logo, formato).
 */
export function neuroDesignDefaultConfig() {
  return {
    user_ai_connection_id: null,
    subject_enabled: true,
    subject_gender: 'feminino',
    subject_description: '',
    subject_image_urls: [],
    quantity: 1,
    layout_position: 'centro',
    dimensions: '1:1',
    text_enabled: false,
    text_mode: 'structured',
    custom_text: '',
    custom_text_font_description: '',
    use_reference_image_text: false,
    headline_h1: '',
    subheadline_h2: '',
    cta_button_text: '',
    text_position: 'centro',
    text_gradient: false,
    text_font: '',
    text_color: '',
    text_shape_enabled: false,
    text_shape_style: 'rounded_rectangle',
    text_shape_color: '',
    headline_position: '',
    subheadline_position: '',
    cta_position: '',
    headline_font: '',
    headline_color: '',
    headline_shape_enabled: false,
    headline_shape_style: 'rounded_rectangle',
    headline_shape_color: '',
    headline_zone: '',
    subheadline_font: '',
    subheadline_color: '',
    subheadline_shape_enabled: false,
    subheadline_shape_style: 'rounded_rectangle',
    subheadline_shape_color: '',
    subheadline_zone: '',
    cta_font: '',
    cta_color: '',
    cta_shape_enabled: false,
    cta_shape_style: 'rounded_rectangle',
    cta_shape_color: '',
    cta_zone: '',
    logo_url: '',
    niche_project: '',
    environment: '',
    use_scenario_photos: false,
    scenario_photo_urls: [],
    ambient_color: '',
    rim_light_color: '',
    fill_light_color: '',
    shot_type: 'medio busto',
    floating_elements_enabled: false,
    floating_elements_text: '',
    style_reference_urls: [],
    style_reference_instructions: [],
    visual_attributes: {
      sobriety: 50,
      style_tags: [],
      ultra_realistic: false,
      blur_enabled: false,
      lateral_gradient_enabled: false,
    },
    additional_prompt: '',
    image_size: '1K',
  };
}
