-- Meta Ads: contas de anúncio, conjuntos (adsets), anúncios (ads) e métricas por nível.
-- Hierarquia: conta -> campanha -> conjunto -> anúncio.

-- 1. Contas de anúncio
CREATE TABLE IF NOT EXISTS public.meta_ads_accounts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  integration_id BIGINT NOT NULL REFERENCES public.meta_ads_integrations(id) ON DELETE CASCADE,
  meta_account_id TEXT NOT NULL,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(integration_id, meta_account_id)
);
CREATE INDEX IF NOT EXISTS idx_meta_ads_accounts_integration ON public.meta_ads_accounts(integration_id);
ALTER TABLE public.meta_ads_accounts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users read own meta_ads_accounts" ON public.meta_ads_accounts;
CREATE POLICY "Users read own meta_ads_accounts"
  ON public.meta_ads_accounts FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.meta_ads_integrations i WHERE i.id = integration_id AND i.user_id = auth.uid()));
GRANT ALL ON public.meta_ads_accounts TO authenticated;
GRANT ALL ON public.meta_ads_accounts TO service_role;

-- 2. Conjuntos de anúncios (adsets)
CREATE TABLE IF NOT EXISTS public.meta_ads_adsets (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  integration_id BIGINT NOT NULL REFERENCES public.meta_ads_integrations(id) ON DELETE CASCADE,
  meta_campaign_id TEXT NOT NULL,
  meta_adset_id TEXT NOT NULL,
  name TEXT,
  campaign_id BIGINT REFERENCES public.meta_ads_campaigns(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(integration_id, meta_adset_id)
);
CREATE INDEX IF NOT EXISTS idx_meta_ads_adsets_integration ON public.meta_ads_adsets(integration_id);
CREATE INDEX IF NOT EXISTS idx_meta_ads_adsets_campaign ON public.meta_ads_adsets(meta_campaign_id);
ALTER TABLE public.meta_ads_adsets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users read own meta_ads_adsets" ON public.meta_ads_adsets;
CREATE POLICY "Users read own meta_ads_adsets"
  ON public.meta_ads_adsets FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.meta_ads_integrations i WHERE i.id = integration_id AND i.user_id = auth.uid()));
GRANT ALL ON public.meta_ads_adsets TO authenticated;
GRANT ALL ON public.meta_ads_adsets TO service_role;

-- 3. Anúncios (ads)
CREATE TABLE IF NOT EXISTS public.meta_ads_ads (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  integration_id BIGINT NOT NULL REFERENCES public.meta_ads_integrations(id) ON DELETE CASCADE,
  meta_adset_id TEXT NOT NULL,
  meta_ad_id TEXT NOT NULL,
  name TEXT,
  adset_id BIGINT REFERENCES public.meta_ads_adsets(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(integration_id, meta_ad_id)
);
CREATE INDEX IF NOT EXISTS idx_meta_ads_ads_integration ON public.meta_ads_ads(integration_id);
CREATE INDEX IF NOT EXISTS idx_meta_ads_ads_adset ON public.meta_ads_ads(meta_adset_id);
ALTER TABLE public.meta_ads_ads ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users read own meta_ads_ads" ON public.meta_ads_ads;
CREATE POLICY "Users read own meta_ads_ads"
  ON public.meta_ads_ads FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.meta_ads_integrations i WHERE i.id = integration_id AND i.user_id = auth.uid()));
GRANT ALL ON public.meta_ads_ads TO authenticated;
GRANT ALL ON public.meta_ads_ads TO service_role;

-- 4. meta_ads_campaigns: adicionar meta_account_id se não existir
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'meta_ads_campaigns' AND column_name = 'meta_account_id') THEN
    ALTER TABLE public.meta_ads_campaigns ADD COLUMN meta_account_id TEXT;
  END IF;
END $$;

-- 5. meta_ads_metrics: adicionar integration_id, date_start, date_stop, level, meta_entity_id se não existirem
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'meta_ads_metrics' AND column_name = 'integration_id') THEN
    ALTER TABLE public.meta_ads_metrics ADD COLUMN integration_id BIGINT REFERENCES public.meta_ads_integrations(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'meta_ads_metrics' AND column_name = 'date_start') THEN
    ALTER TABLE public.meta_ads_metrics ADD COLUMN date_start DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'meta_ads_metrics' AND column_name = 'date_stop') THEN
    ALTER TABLE public.meta_ads_metrics ADD COLUMN date_stop DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'meta_ads_metrics' AND column_name = 'level') THEN
    ALTER TABLE public.meta_ads_metrics ADD COLUMN level TEXT DEFAULT 'campaign';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'meta_ads_metrics' AND column_name = 'meta_entity_id') THEN
    ALTER TABLE public.meta_ads_metrics ADD COLUMN meta_entity_id TEXT;
  END IF;
END $$;

-- Backfill: preencher level e meta_entity_id para registros existentes (campanha)
UPDATE public.meta_ads_metrics SET level = 'campaign', meta_entity_id = meta_campaign_id WHERE level IS NULL AND meta_campaign_id IS NOT NULL;
UPDATE public.meta_ads_metrics SET level = 'campaign' WHERE level IS NULL;
UPDATE public.meta_ads_metrics SET meta_entity_id = meta_campaign_id WHERE meta_entity_id IS NULL AND meta_campaign_id IS NOT NULL;

-- Backfill date_start/date_stop a partir de date se existir
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'meta_ads_metrics' AND column_name = 'date') THEN
    UPDATE public.meta_ads_metrics SET date_start = date, date_stop = date WHERE date_start IS NULL AND date IS NOT NULL;
  END IF;
END $$;

-- Índices para métricas por nível
CREATE INDEX IF NOT EXISTS idx_meta_ads_metrics_integration_level ON public.meta_ads_metrics(integration_id, level);
CREATE INDEX IF NOT EXISTS idx_meta_ads_metrics_meta_entity ON public.meta_ads_metrics(meta_entity_id) WHERE meta_entity_id IS NOT NULL;
