-- Vários contextos por cliente (substitui um único context_document)
-- clients.id é bigint, então client_id deve ser bigint
CREATE TABLE IF NOT EXISTS client_contexts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id bigint NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  name text,
  content text NOT NULL DEFAULT '',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_client_contexts_client_id ON client_contexts(client_id);

-- Permissões: roles do Supabase precisam poder usar a tabela (RLS filtra por linha)
GRANT ALL ON client_contexts TO authenticated;
GRANT ALL ON client_contexts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE client_contexts_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE client_contexts_id_seq TO service_role;

-- RLS: usuário só acessa contextos dos próprios clientes
ALTER TABLE client_contexts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "client_contexts_select_own" ON client_contexts;
CREATE POLICY "client_contexts_select_own" ON client_contexts
  FOR SELECT USING (
    client_id IN (SELECT id FROM clients WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "client_contexts_insert_own" ON client_contexts;
CREATE POLICY "client_contexts_insert_own" ON client_contexts
  FOR INSERT WITH CHECK (
    client_id IN (SELECT id FROM clients WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "client_contexts_update_own" ON client_contexts;
CREATE POLICY "client_contexts_update_own" ON client_contexts
  FOR UPDATE USING (
    client_id IN (SELECT id FROM clients WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "client_contexts_delete_own" ON client_contexts;
CREATE POLICY "client_contexts_delete_own" ON client_contexts
  FOR DELETE USING (
    client_id IN (SELECT id FROM clients WHERE user_id = auth.uid())
  );

-- Migrar contexto único existente para a nova tabela (se a coluna context_document existir)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'clients' AND column_name = 'context_document') THEN
    INSERT INTO client_contexts (client_id, name, content)
    SELECT id, 'Contexto', COALESCE(context_document, '')
    FROM clients
    WHERE TRIM(COALESCE(context_document, '')) <> '';
  END IF;
END $$;

-- Comentário: a coluna clients.context_document pode ser mantida ou removida depois com:
-- ALTER TABLE clients DROP COLUMN IF EXISTS context_document;
